import beerStyles from "./beer-styles.js";


const breweries = [
  {
    id: "guinness",
    name: "Guinness Brewery",
    description: "Founded in 1759 in Dublin, it's one of the world's most iconic breweries, known for Guinness Stout. The Guinness legacy runs much deeper than just creating delicious brews. Arthur Guinness felt it was important to give back to the city that hosts the brewery. This legacy of philanthropic tradition was in turn passed on from father to son for seven generations, and still lives on within Guinness today.",
    country: "Ireland",
    image: "https://images.squarespace-cdn.com/content/v1/5876279bbebafb82a7c81c00/1617043580504-VIPP3ZSKF8I7WMY3CRFK/DSCN5229.JPG",
    link: "https://www.guinness.com/en",
    beers: [
      {
        id: "guinness-draught",
        name: "Guinness Draught",
        style: beerStyles.find((s) => s.id === "stout"),
        abv: "4.2%",
        image: "https://shop.guinness-storehouse.com/cdn/shop/files/Guinness_Pint_Glass_and_Can_Gift_Set.jpg?v=1731694599&width=1214",
        link: "https://www.guinness.com/en/beers/guinness-draught",
      },
      {
        id: "guinness-extra-stout",
        name: "Guinness Extra Stout",
        style: beerStyles.find((s) => s.id === "stout"),
        abv: "5.6%",
        image: "https://shop.guinness-storehouse.com/cdn/shop/files/Guinness_Pint_Glass_and_Can_Gift_Set.jpg?v=1731694599&width=1214",
        link: "https://www.guinness.com/en/beers/guinness-original",
      },
      {
        id: "guinness-extra-stout",
        name: "Guinness Extra Stout",
        style: beerStyles.find((s) => s.id === "stout"),
        abv: "5.6%",
        image: "https://shop.guinness-storehouse.com/cdn/shop/files/Guinness_Pint_Glass_and_Can_Gift_Set.jpg?v=1731694599&width=1214",
        link: "https://www.guinness.com/en/beers/guinness-original",
      },
      {
        id: "guinness-extra-stout",
        name: "Guinness Extra Stout",
        style: beerStyles.find((s) => s.id === "stout"),
        abv: "5.6%",
        image: "https://shop.guinness-storehouse.com/cdn/shop/files/Guinness_Pint_Glass_and_Can_Gift_Set.jpg?v=1731694599&width=1214",
        link: "https://www.guinness.com/en/beers/guinness-original",
      },
    ],
  },
  {
    id: "brewdog",
    name: "BrewDog",
    description: "A modern Scottish brewery known for its bold and creative approach to craft beer.",
    country: "Scotland",
    image: "https://brewdog.com/cdn/shop/files/Punk_Falling_-_Landing_Page_Promotion.png?v=1750894122&width=2048",
    link: "https://brewdog.com/",
    beers: [
      {
        id: "punk-ipa",
        name: "Punk IPA",
        style: beerStyles.find((s) => s.id === "ipa"),
        abv: "5.6%",
        image: "https://brewdog.com/cdn/shop/files/Punk_Falling_-_Landing_Page_Promotion.png?v=1750894122&width=2048",
        link: "https://brewdog.com/products/punk-ipa",
      },
      {
        id: "dead-pony-club",
        name: "Dead Pony Club",
        style: beerStyles.find((s) => s.id === "pale-ale"),
        abv: "3.8%",
        image: "https://brewdog.com/cdn/shop/files/Punk_Falling_-_Landing_Page_Promotion.png?v=1750894122&width=2048",
        link: "https://brewdog.com/products/dead-pony-club",
      },
    ],
  },
  {
    id: "weihenstephan",
    name: "Bayerische Staatsbrauerei Weihenstephan",
    description: "Considered the world's oldest brewery, founded around 1040 in Bavaria, Germany.",
    country: "Germany",
    image: "https://www.weihenstephaner.de/_next/image?url=https%3A%2F%2Fwww.weihenstephaner.de%2Fstrapi%2Fuploads%2FEN_AIBA_Print_20x15cm_b3340e379d.jpg&w=640&q=75",
    link: "https://www.weihenstephaner.de/en/",
    beers: [
      {
        id: "weihenstephan-hefeweissbier",
        name: "Hefeweissbier",
        style: beerStyles.find((s) => s.id === "weissbier"),
        abv: "5.4%",
        image: "https://www.weihenstephaner.de/_next/image?url=https%3A%2F%2Fwww.weihenstephaner.de%2Fstrapi%2Fuploads%2FHWB_49be808fd1.png&w=640&q=75",
        link: "https://www.weihenstephaner.de/en/our-beers/wheat-beer",
      },
      {
        id: "weihenstephan-bock",
        name: "Weizenbock Vitus",
        style: beerStyles.find((s) => s.id === "bock"),
        abv: "7.7%",
        image: "https://www.weihenstephaner.de/_next/image?url=https%3A%2F%2Fwww.weihenstephaner.de%2Fstrapi%2Fuploads%2FVitus_ec070d9910.png&w=640&q=75",
        link: "https://www.weihenstephaner.de/en/our-beers/vitus-1",
      },
    ],
  },
  {
    id: "chimay",
    name: "Chimay Brewery",
    description: "A Trappist brewery in Belgium known for its rich, flavorful ales brewed by monks since 1862.",
    country: "Belgium",
    image: "https://chimay.com/wp-content/uploads/2021/09/intro-home-2-min.jpg",
    link: "https://chimay.com/en/taste/our-beers/",
    beers: [
      {
        id: "chimay-bleue",
        name: "Chimay Bleue (Blue)",
        style: beerStyles.find((s) => s.id === "dubbel"),
        abv: "9.0%",
        image: "https://images.tcdn.com.br/img/img_prod/1053976/cerveja_belga_chimay_blue_330_ml_37530_2_846c1b35b3d1864b317cf196678a69fa.jpg",
        link: "https://chimay.com/en/beer/chimay-blue/",
      },
      {
        id: "chimay-tripel",
        name: "Chimay Tripel (White)",
        style: beerStyles.find((s) => s.id === "tripel"),
        abv: "8.0%",
        image: "https://www.birredamanicomio.com/wp-content/uploads/chimay-bianca-33-ok-vp.jpg",
        link: "https://chimay.com/en/beer/chimay-triple/",
      },
    ],
  },
  {
    id: "pedavena",
    name: "Birra Pedavena",
    description: "A historic Italian brewery founded in 1897 at the foot of the Dolomites, known for its classic lagers.",
    country: "Italy",
    image: "https://www.labirreriapedavena.it/wp-content/uploads/2022/03/Sala2a.jpg",
    link: "https://www.labirreriapedavena.it/",
    beers: [
      {
        id: "pedavena-premium",
        name: "Pedavena Premium Lager",
        style: beerStyles.find((s) => s.id === "dunkel"),
        abv: "5.9%",
        image: "https://www.labirreriapedavena.it/wp-content/uploads/2022/03/643_Pedavena_Ambrata_33cl.png",
        link: "https://www.labirreriapedavena.it/birre/pedavena-ambrata/",
      },
      {
        id: "pedavena-speciale",
        name: "Pedavena Speciale",
        style: beerStyles.find((s) => s.id === "lager"),
        abv: "5.9%",
        image: "https://www.labirreriapedavena.it/wp-content/uploads/2022/03/539_Pedavena_Speciale_50cl.png",
        link: "https://www.labirreriapedavena.it/birre/pedavena-speciale/",
      },
    ],
  },
  {
    id: "birra-laru",
    name: "Birra Laru",
    description: "The brand LA RÜ is the synonym of the Italian artisanal beer of the brewery “Bosco Fagarè”, that takes the name from a torrent: the Ru Bianco that was crossing Cornuda city (location of the brewery) from north to south cutting the city in half.",
    country: "Italy",
    image: "https://www.birralaru.it/img/gallery/16-birrificio-la-ru.jpg",
    link: "https://www.birralaru.it/",
    beers: [
      {
        id: "linpha",
        name: "Linpha",
        style: beerStyles.find((s) => s.id === "ipa"),
        abv: "6.8%",
        image: "https://www.birralaru.it/img/prodotti/birra-laru-linfha.png",
        link: "https://www.birralaru.it/en/birra-artigianale/linfha",
      },
      {
        id: "nysa",
        name: "Nysa",
        style: beerStyles.find((s) => s.id === "lager"),
        abv: "4.5%",
        image: "https://www.birralaru.it/img/prodotti/birra-laru-nysa.png",
        link: "https://www.birralaru.it/en/birra-artigianale/nysa",
      },
    ],
  },
  {
    id: "lzo",
    name: "LZO Brewery",
    description: "LZO is an independently run craft brewery located in Conegliano, in the province of Treviso.",
    country: "Italy",
    image: "https://www.pintamedicea.com/birra/wp-content/uploads/2022/03/lzo-beer-03-800x445.jpg",
    link: "https://www.lzo.beer/",
    beers: [
      {
        id: "lzo-candice",
        name: "Candice",
        style: beerStyles.find((s) => s.id === "witbier"),
        abv: "4.2%",
        image: "https://static.wixstatic.com/media/712bad_22a514c765714075b375e440021c6cf8~mv2.png/v1/fill/w_155,h_300,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/LZO_CANDICE_MOCK22.png",
        link: "https://www.lzo.beer/candice",
      },
      {
        id: "lzo-holi",
        name: "Holi",
        style: beerStyles.find((s) => s.id === "saison"),
        abv: "3.8%",
        image: "https://static.wixstatic.com/media/712bad_f91743e9b8914162878838928c08d70c~mv2.png/v1/fill/w_181,h_350,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/LZO_HOLI_MOCK22_edited.png",
        link: "https://www.lzo.beer/holi",
      },
    ],
  },
  {
    id: "garlatti-costa",
    name: "Garlatti Costa",
    description: "A small artisan brewery from Friuli Venezia Giulia producing high-quality beers with local character.",
    country: "Italy",
    image: "https://www.birraandsound.it/wp-content/uploads/2019/02/birrificio-garlatti.jpg",
    link: "https://www.birragarlatticosta.it/",
    beers: [
      {
        id: "garlatti-rushmore",
        name: "Rushmore",
        style: beerStyles.find((s) => s.id === "pale-ale"),
        abv: "5.5%",
        image: "https://www.birragarlatticosta.it/wp-content/uploads/2024/01/rushmore33.png",
        link: "https://www.birragarlatticosta.it/product/rushmore/",
      },
      {
        id: "garlatti-tilt",
        name: "Tilt",
        style: beerStyles.find((s) => s.id === "ipa"),
        abv: "6.7%",
        image: "https://www.birragarlatticosta.it/wp-content/uploads/2024/01/tilt33-1.png",
        link: "https://www.birragarlatticosta.it/product/tilt/",
      },
    ],
  },
  {
    id: "birra-di-naon",
    name: "Birra di Naon",
    description: "A Friulian craft brewery combining tradition and creativity with carefully selected ingredients.",
    country: "Italy",
    image: "https://birradinaon.com/wp-content/uploads/2023/01/06082021-_DSC5387-1.jpg",
    link: "https://birradinaon.com/",
    beers: [
      {
        id: "naon-medunia",
        name: "Medunia",
        style: beerStyles.find((s) => s.id === "lager"),
        abv: "5.1%",
        image: "https://birradinaon.com/wp-content/uploads/2021/09/MEDUNIA.png",
        link: "https://birradinaon.com/prodotto/medunia-75-cl/",
      },
      {
        id: "naon-sol-invictus",
        name: "Sol Invictus",
        style: beerStyles.find((s) => s.id === "blonde-ale"),
        abv: "7.0%",
        image: "https://birradinaon.com/wp-content/uploads/2022/01/blanc-3-1-3-1-3.png",
        link: "https://birradinaon.com/prodotto/sol-invictus-75cl/",
      },
    ],
  },
];

export default breweries;
