import beerStyles from "./beer-styles.js";


const breweries = [
  {
    id: "guinness",
    name: "Guinness Brewery",
    description: "Founded in 1759 in Dublin, it's one of the world's most iconic breweries, known for Guinness Stout.",
    country: "Ireland",
    image: "https://upload.wikimedia.org/wikipedia/commons/3/34/Guinness_Storehouse.jpg",
    link: "https://www.guinness.com/en",
    beers: [
      {
        id: "guinness-draught",
        name: "Guinness Draught",
        style: beerStyles.find((s) => s.id === "stout"),
        abv: "4.2%",
        image: "https://m.media-amazon.com/images/I/61Dk2xGdVPL._SL1500_.jpg",
        link: "https://www.guinness.com/en/beers/guinness-draught",
      },
      {
        id: "guinness-extra-stout",
        name: "Guinness Extra Stout",
        style: beerStyles.find((s) => s.id === "stout"),
        abv: "5.6%",
        image: "https://m.media-amazon.com/images/I/71g06rSXmoL._SL1500_.jpg",
        link: "https://www.guinness.com/en/beers/guinness-original",
      },
    ],
  },
  {
    id: "brewdog",
    name: "BrewDog",
    description: "A modern Scottish brewery known for its bold and creative approach to craft beer.",
    country: "Scotland",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/af/BrewDog_Bar.jpg",
    link: "https://brewdog.com/",
    beers: [
      {
        id: "punk-ipa",
        name: "Punk IPA",
        style: beerStyles.find((s) => s.id === "ipa"),
        abv: "5.6%",
        image: "https://brewdog.com/cdn/shop/files/Punk_Falling_-_Landing_Page_Promotion.png?v=1750894122&width=2048",
        link: "https://brewdog.com/products/punk-ipa",
      },
      {
        id: "dead-pony-club",
        name: "Dead Pony Club",
        style: beerStyles.find((s) => s.id === "pale-ale"),
        abv: "3.8%",
        image: "https://m.media-amazon.com/images/I/71iY6gI2nYL._SL1500_.jpg",
        link: "https://brewdog.com/products/dead-pony-club",
      },
    ],
  },
  {
    id: "weihenstephan",
    name: "Bayerische Staatsbrauerei Weihenstephan",
    description: "Considered the world's oldest brewery, founded around 1040 in Bavaria, Germany.",
    country: "Germany",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Weihenstephan_Brewery.jpg",
    link: "https://www.weihenstephaner.com/",
    beers: [
      {
        id: "weihenstephan-hefeweissbier",
        name: "Hefeweissbier",
        style: beerStyles.find((s) => s.id === "weissbier"),
        abv: "5.4%",
        image: "https://www.weihenstephaner.com/wp-content/uploads/2021/06/Weissbier.png",
        link: "https://www.weihenstephaner.com/our-beers/hefe-weissbier/",
      },
      {
        id: "weihenstephan-dunkel",
        name: "Hefeweissbier Dunkel",
        style: beerStyles.find((s) => s.id === "dunkel"),
        abv: "5.3%",
        image: "https://www.weihenstephaner.com/wp-content/uploads/2021/06/Dunkel.png",
        link: "https://www.weihenstephaner.com/our-beers/hefeweissbier-dunkel/",
      },
    ],
  },
  {
    id: "chimay",
    name: "Chimay Brewery",
    description: "A Trappist brewery in Belgium known for its rich, flavorful ales brewed by monks since 1862.",
    country: "Belgium",
    image: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Abbaye_de_Sc_ourmont_-_Brewery.jpg",
    link: "https://chimay.com/en/",
    beers: [
      {
        id: "chimay-bleue",
        name: "Chimay Bleue (Blue)",
        style: beerStyles.find((s) => s.id === "dubbel"),
        abv: "9.0%",
        image: "https://chimay.com/wp-content/uploads/2020/09/ChimayBleue-1.png",
        link: "https://chimay.com/en/beer/chimay-blue/",
      },
      {
        id: "chimay-tripel",
        name: "Chimay Tripel (White)",
        style: beerStyles.find((s) => s.id === "tripel"),
        abv: "8.0%",
        image: "https://chimay.com/wp-content/uploads/2020/09/ChimayBlanche.png",
        link: "https://chimay.com/en/beer/chimay-triple/",
      },
    ],
  },
  {
    id: "pedavena",
    name: "Birra Pedavena",
    description: "A historic Italian brewery founded in 1897 at the foot of the Dolomites, known for its classic lagers.",
    country: "Italy",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Birrificio_di_Pedavena.jpg",
    link: "https://www.birrapedavena.it/",
    beers: [
      {
        id: "pedavena-premium",
        name: "Pedavena Premium Lager",
        style: beerStyles.find((s) => s.id === "helles"),
        abv: "4.8%",
        image: "https://www.birrapedavena.it/wp-content/uploads/2019/04/Pedavena-Premium.png",
        link: "https://www.birrapedavena.it/prodotti/pedavena-premium/",
      },
      {
        id: "pedavena-speciale",
        name: "Pedavena Speciale",
        style: beerStyles.find((s) => s.id === "amber-ale"),
        abv: "5.5%",
        image: "https://www.birrapedavena.it/wp-content/uploads/2019/04/Pedavena-Speciale.png",
        link: "https://www.birrapedavena.it/prodotti/pedavena-speciale/",
      },
    ],
  },
  {
    id: "birra-laru",
    name: "Birra Laru",
    description: "The brand LA RÜ is the synonym of the Italian artisanal beer of the brewery “Bosco Fagarè”, that takes the name from a torrent: the Ru Bianco that was crossing Cornuda city (location of the brewery) from north to south cutting the city in half.",
    country: "Italy",
    image: "https://www.birralaru.it/img/gallery/16-birrificio-la-ru.jpg",
    link: "https://www.birralaru.it/",
    beers: [
      {
        id: "linpha",
        name: "Linpha",
        style: beerStyles.find((s) => s.id === "ipa"),
        abv: "6.8%",
        image: "https://www.birralaru.it/img/prodotti/birra-laru-linfha.png",
        link: "https://www.birralaru.it/en/birra-artigianale/linfha",
      },
      {
        id: "nysa",
        name: "Nysa",
        style: beerStyles.find((s) => s.id === "lager"),
        abv: "4.5%",
        image: "https://www.birralaru.it/img/prodotti/birra-laru-nysa.png",
        link: "https://www.birralaru.it/en/birra-artigianale/nysa",
      },
    ],
  },
  {
    id: "lzo",
    name: "LZO Brewery",
    description: "LZO is an independently run craft brewery located in Conegliano, in the province of Treviso.",
    country: "Italy",
    image: "https://www.lzo.beer/wp-content/uploads/2021/11/LZO-brewery.jpg",
    link: "https://www.lzo.beer/",
    beers: [
      {
        id: "lzo-candice",
        name: "Candice",
        style: beerStyles.find((s) => s.id === "witbier"),
        abv: "4.2%",
        image: "https://static.wixstatic.com/media/712bad_22a514c765714075b375e440021c6cf8~mv2.png/v1/fill/w_155,h_300,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/LZO_CANDICE_MOCK22.png",
        link: "https://www.lzo.beer/candice",
      },
      {
        id: "lzo-holi",
        name: "Holi",
        style: beerStyles.find((s) => s.id === "saison"),
        abv: "3.8%",
        image: "https://static.wixstatic.com/media/712bad_f91743e9b8914162878838928c08d70c~mv2.png/v1/fill/w_181,h_350,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/LZO_HOLI_MOCK22_edited.png",
        link: "https://www.lzo.beer/holi",
      },
    ],
  },
  {
    id: "garlatti-costa",
    name: "Garlatti Costa",
    description: "A small artisan brewery from Friuli Venezia Giulia producing high-quality beers with local character.",
    country: "Italy",
    image: "https://www.garlatticosta.it/wp-content/uploads/2021/04/garlatti-brewery.jpg",
    link: "https://www.garlatticosta.it/",
    beers: [
      {
        id: "garlatti-solaris",
        name: "Solaris",
        style: beerStyles.find((s) => s.id === "pilsner"),
        abv: "5.0%",
        image: "https://www.garlatticosta.it/wp-content/uploads/2020/09/Solaris.png",
        link: "https://www.garlatticosta.it/prodotto/solaris/",
      },
      {
        id: "garlatti-darkwood",
        name: "Darkwood",
        style: beerStyles.find((s) => s.id === "stout"),
        abv: "6.2%",
        image: "https://www.garlatticosta.it/wp-content/uploads/2020/09/Darkwood.png",
        link: "https://www.garlatticosta.it/prodotto/darkwood/",
      },
    ],
  },
  {
    id: "birra-di-naon",
    name: "Birra di Naon",
    description: "A Friulian craft brewery combining tradition and creativity with carefully selected ingredients.",
    country: "Italy",
    image: "https://www.birradinaon.it/wp-content/uploads/2023/01/naon-brewery.jpg",
    link: "https://www.birradinaon.it/",
    beers: [
      {
        id: "naon-ambra",
        name: "Ambra",
        style: beerStyles.find((s) => s.id === "amber-ale"),
        abv: "5.5%",
        image: "https://www.birradinaon.it/wp-content/uploads/2023/01/Ambra.png",
        link: "https://www.birradinaon.it/prodotto/ambra/",
      },
      {
        id: "naon-bionda",
        name: "Bionda",
        style: beerStyles.find((s) => s.id === "helles"),
        abv: "4.9%",
        image: "https://www.birradinaon.it/wp-content/uploads/2023/01/Bionda.png",
        link: "https://www.birradinaon.it/prodotto/bionda/",
      },
    ],
  },
];

export default breweries;
